eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8000
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/properties
  profiles:
    active: native